refactor(runas): format

diff --git a/runas b/runas
--- a/runas
+++ b/runas
@@ -5,12 +5,12 @@ help() {
 }
 
 if [[ $1 == "-h" || $1 == "--help" ]]; then
- help
+  help
 elif [[ $# < 4 ]]; then
- printf "\x1b[31mInvalid no of args\x1b[0m\n"
- help
- exit 1
-fi 
+  printf "\x1b[31mInvalid no of args\x1b[0m\n"
+  help
+  exit 1
+fi
 
 printf "\x1b[32m%s@%s\x1b[0m:\x1b[34m%s\x1b[0m\$ %s\n" "$1" "$2" "$3" "$4"
 exec $4
